nifty50=["CIPLA.NS","WIPRO.NS","HEROMOTOCO.NS","BAJAJ-AUTO.NS","NESTLEIND.NS","BAJFINANCE.NS","ITC.NS","HINDALCO.NS","MARUTI.NS",
        "TCS.NS","GRASIM.NS","ZEEL.NS","ULTRACEMCO.NS","LT.NS","TATASTEEL.NS","SHREECEM.NS","ICICIBANK.NS","TITAN.NS","INDUSINDBK.NS",
        "MM.NS","NTPC.NS","BHARTIARTL.NS","BAJAJFINSV.NS","KOTAKBANK.NS","TECHM.NS","BRITANNIA.NS","ONGC.NS","RELIANCE.NS","GAIL.NS"]

